services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-backend-app
    container_name: chat_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - chat-network

  nginx:
    image: nginx:alpine
    container_name: chat_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - chat-network

  db:
    image: mongo:latest
    container_name: chat_mongo
    restart: unless-stopped
    ports:
      - "27017:27017" # Exposed for local tools, but app uses 'db' hostname
    environment:
      MONGO_INITDB_DATABASE: chat_db
    volumes:
      - mongo_data:/data/db
    networks:
      - chat-network

  mailhog:
    image: mailhog/mailhog
    container_name: chat_mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # UI port
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
